import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#061b17]/75 px-6 py-2 backdrop-blur-xl sm:px-10 lg:px-20">
      <nav className="mx-auto flex max-w-7xl items-center justify-between">
        <a href="#" className="flex items-center gap-3">
          <Image
            src="/akshayapatra-logo-v2.png"
            alt="AkshayaPatra logo"
            width={70}
            height={70}
            className=""
          />
          <div>
            <p className="text-lg font-bold leading-none text-white">
              AkshayaPatra
            </p>
            <p className="mt-1 text-xs text-[#f5b618]">
              Tailor | Automate | Scale
            </p>
          </div>
        </a>

        <div className="hidden items-center gap-8 text-lg font-medium text-white/70 md:flex">
          <a href="#" className="transition hover:text-[#f5b618]">
            Home
          </a>
          <a href="#services" className="transition hover:text-[#f5b618]">
            Services
          </a>
          <a href="#contact" className="transition hover:text-[#f5b618]">
            Contact
          </a>
        </div>

        <a
          href="#contact"
          className="hidden rounded-full border border-[#f5b618]/40 px-5 py-2.5 text-sm font-semibold text-[#f5b618] transition hover:bg-[#f5b618] hover:text-[#061b17] sm:inline-flex"
        >
          Get Started
        </a>
      </nav>
    </header>
  );
}

function Footer() {
  return (
    <footer className="border-t border-white/10 px-6 py-10 sm:px-10 lg:px-20">
      <div className="mx-auto grid max-w-7xl gap-8 text-sm text-white/60 md:grid-cols-3">
        {/* Brand */}
        <div>
          <p className="text-white font-semibold text-lg">AkshayaPatra</p>
          <p className="mt-2 text-white/50">
            © {new Date().getFullYear()} All rights reserved.
          </p>
        </div>

        {/* Links */}
        <div className="flex flex-col gap-2">
          <a href="#" className="transition hover:text-[#f5b618]">
            Privacy
          </a>
          <a href="#" className="transition hover:text-[#f5b618]">
            Terms
          </a>
          <a href="#contact" className="transition hover:text-[#f5b618]">
            Contact
          </a>
        </div>

        {/* Contact Info */}
        <div className="flex flex-col gap-2">
          <a href="tel:9199141293" className="hover:text-[#f5b618]">
            919-914-1293
          </a>
          <a
            href="mailto:Corporateservices@kazanc.app"
            className="hover:text-[#f5b618]"
          >
            Corporateservices@kazanc.app
          </a>
          <p>1121, Lowland Street, Apex, NC - 27523</p>
        </div>
      </div>
    </footer>
  );
}
